export type BuildingStatus = 'live' | 'coming_soon';
export type BuildingComponent = 'library' | 'school' | 'lab' | 'home' | 'theater';

export interface BuildingConfig {
  id: string;
  name: string;
  subtitle: string;
  icon: string;
  position: [number, number, number];
  color: string;
  roofColor: string;
  serviceUrl: string;
  status: BuildingStatus;
  component: BuildingComponent;
}

export const BUILDINGS: BuildingConfig[] = [
  {
    id: 'seedling',
    name: '새싹 발달관',
    subtitle: 'AI 발달 관찰',
    icon: '🌱',
    position: [0, 0, 8],
    color: '#bbf7d0',
    roofColor: '#22c55e',
    serviceUrl: 'https://seedling.genomic.cc',
    status: 'live',
    component: 'home',
  },
  {
    id: 'math',
    name: '숲의 수학관',
    subtitle: '수/논리 놀이',
    icon: '🔢',
    position: [0, 0, 4],
    color: '#bfdbfe',
    roofColor: '#3b82f6',
    serviceUrl: 'https://math.genomic.cc',
    status: 'live',
    component: 'lab',
  },
  {
    id: 'media',
    name: '미디어 극장',
    subtitle: '미디어 리터러시',
    icon: '🎬',
    position: [-6, 0, 0],
    color: '#e9d5ff',
    roofColor: '#9333ea',
    serviceUrl: 'https://media.genomic.cc',
    status: 'live',
    component: 'theater',
  },
  {
    id: 'library',
    name: '독서 도서관',
    subtitle: 'AI 동화 생성',
    icon: '📖',
    position: [-7, 0, 5],
    color: '#fed7aa',
    roofColor: '#f97316',
    serviceUrl: '/story',
    status: 'live',
    component: 'library',
  },
  {
    id: 'hangul',
    name: '한글 학교',
    subtitle: '자음·모음 학습',
    icon: '🔤',
    position: [-5, 0, 3],
    color: '#fecdd3',
    roofColor: '#e11d48',
    serviceUrl: '/hangul',
    status: 'live',
    component: 'school',
  },
  {
    id: 'english',
    name: '영어 마을',
    subtitle: 'ABC·단어·퀴즈',
    icon: '🌍',
    position: [5, 0, 3],
    color: '#fef08a',
    roofColor: '#ca8a04',
    serviceUrl: '/english',
    status: 'live',
    component: 'school',
  },
  {
    id: 'music',
    name: '음악의 집',
    subtitle: '악기·피아노·리듬',
    icon: '🎵',
    position: [-5, 0, -3],
    color: '#fbcfe8',
    roofColor: '#db2777',
    serviceUrl: '/music',
    status: 'live',
    component: 'home',
  },
  {
    id: 'art',
    name: '미술 갤러리',
    subtitle: '그림·도장·색 섞기',
    icon: '🎨',
    position: [5, 0, -3],
    color: '#ffedd5',
    roofColor: '#ea580c',
    serviceUrl: '/art',
    status: 'live',
    component: 'library',
  },
  {
    id: 'science',
    name: '과학 연구소',
    subtitle: '동물·실험·별자리',
    icon: '🔬',
    position: [-7, 0, -1],
    color: '#d1fae5',
    roofColor: '#059669',
    serviceUrl: '/science',
    status: 'live',
    component: 'lab',
  },
  {
    id: 'creative',
    name: '창의 놀이터',
    subtitle: '패턴·점잇기·모양',
    icon: '🧩',
    position: [7, 0, 0],
    color: '#ede9fe',
    roofColor: '#7c3aed',
    serviceUrl: '/creative',
    status: 'live',
    component: 'lab',
  },
  {
    id: 'emotion',
    name: '감정 쉼터',
    subtitle: '감정 카드·기분 체크',
    icon: '😊',
    position: [7, 0, 5],
    color: '#ffe4e6',
    roofColor: '#f43f5e',
    serviceUrl: '/emotion',
    status: 'live',
    component: 'home',
  },
];
